package sharedjob

type CargoType string

const (
	None                CargoType = "None"
	Coal                CargoType = "Coal"
	IronOre             CargoType = "IronOre"
	CrudeOil            CargoType = "CrudeOil"
	Diesel              CargoType = "Diesel"
	Gasoline            CargoType = "Gasoline"
	Methane             CargoType = "Methane"
	Logs                CargoType = "Logs"
	Boards              CargoType = "Boards"
	Plywood             CargoType = "Plywood"
	Wheat               CargoType = "Wheat"
	Corn                CargoType = "Corn"
	Pigs                CargoType = "Pigs"
	Cows                CargoType = "Cows"
	Chickens            CargoType = "Chickens"
	Sheep               CargoType = "Sheep"
	Goats               CargoType = "Goats"
	Bread               CargoType = "Bread"
	DairyProducts       CargoType = "DairyProducts"
	MeatProducts        CargoType = "MeatProducts"
	CannedFood          CargoType = "CannedFood"
	CatFood             CargoType = "CatFood"
	SteelRolls          CargoType = "SteelRolls"
	SteelBillets        CargoType = "SteelBillets"
	SteelSlabs          CargoType = "SteelSlabs"
	SteelBentPlates     CargoType = "SteelBentPlates"
	SteelRails          CargoType = "SteelRails"
	ScrapMetal          CargoType = "ScrapMetal"
	ElectronicsIskar    CargoType = "ElectronicsIskar"
	ElectronicsKrugmann CargoType = "ElectronicsKrugmann"
	ElectronicsAAG      CargoType = "ElectronicsAAG"
	ElectronicsNovae    CargoType = "ElectronicsNovae"
	ElectronicsTraeg    CargoType = "ElectronicsTraeg"
	ToolsIskar          CargoType = "ToolsIskar"
	ToolsBrohm          CargoType = "ToolsBrohm"
	ToolsAAG            CargoType = "ToolsAAG"
	ToolsNovae          CargoType = "ToolsNovae"
	ToolsTraeg          CargoType = "ToolsTraeg"
	Furniture           CargoType = "Furniture"
	Pipes               CargoType = "Pipes"
	ClothingObco        CargoType = "ClothingObco"
	ClothingNeoGamma    CargoType = "ClothingNeoGamma"
	ClothingNovae       CargoType = "ClothingNovae"
	ClothingTraeg       CargoType = "ClothingTraeg"
	Medicine            CargoType = "Medicine"
	ChemicalsIskar      CargoType = "ChemicalsIskar"
	ChemicalsSperex     CargoType = "ChemicalsSperex"
	NewCars             CargoType = "NewCars"
	ImportedNewCars     CargoType = "ImportedNewCars"
	Tractors            CargoType = "Tractors"
	Excavators          CargoType = "Excavators"
	Alcohol             CargoType = "Alcohol"
	Acetylene           CargoType = "Acetylene"
	CryoOxygen          CargoType = "CryoOxygen"
	CryoHydrogen        CargoType = "CryoHydrogen"
	Argon               CargoType = "Argon"
	Nitrogen            CargoType = "Nitrogen"
	Ammonia             CargoType = "Ammonia"
	SodiumHydroxide     CargoType = "SodiumHydroxide"
	SpentNuclearFuel    CargoType = "SpentNuclearFuel"
	Ammunition          CargoType = "Ammunition"
	Biohazard           CargoType = "Biohazard"
	Tanks               CargoType = "Tanks"
	MilitaryTrucks      CargoType = "MilitaryTrucks"
	MilitarySupplies    CargoType = "MilitarySupplies"
	EmptySunOmni        CargoType = "EmptySunOmni"
	EmptyIskar          CargoType = "EmptyIskar"
	EmptyObco           CargoType = "EmptyObco"
	EmptyGoorsk         CargoType = "EmptyGoorsk"
	EmptyKrugmann       CargoType = "EmptyKrugmann"
	EmptyBrohm          CargoType = "EmptyBrohm"
	EmptyAAG            CargoType = "EmptyAAG"
	EmptySperex         CargoType = "EmptySperex"
	EmptyNovae          CargoType = "EmptyNovae"
	EmptyTraeg          CargoType = "EmptyTraeg"
	EmptyChemlek        CargoType = "EmptyChemlek"
	EmptyNeoGamma       CargoType = "EmptyNeoGamma"
)

func (ct CargoType) String() string {
	return string(ct)
}
