// Code generated by "jade.go"; DO NOT EDIT.

package ui

import (
	"io"

	"github.com/Joker/hpp"
	"github.com/devnull-twitch/sharedjob-server"
)

const (
	connections__0 = `<!DOCTYPE html><html lang="en">`
	connections__1 = `<head>`
	connections__2 = `<title>Our little derail valley - `
	connections__3 = `</title><meta name="viewport" content="width=device-width, initial-scale=1"/><script src="https://unpkg.com/htmx.org@1.9.6"></script><style>      @import "https://unpkg.com/bulma@0.9.4/css/bulma.min.css";</style></head><body><nav class="navbar" role="navigation"><div class="navbar-menu"><div class="navbar-start"><a class="navbar-item" href="/ui/jobs">Jobs</a><a class="navbar-item" href="/ui/stations">Stations</a><a class="navbar-item" href="/ui/connections">Connected players</a></div></div></nav><section class="section"><div class="container is-fullhd"><h1 class="title">`
	connections__4 = `</h1><p>List of all connected player</p><table class="table is-fullwidth is-striped"><thead><tr><th>Name</th></tr></thead><tbody id="player-table">`
	connections__5 = `</tbody></table><div id="modal-target"></div></div></section></body></html>`
	connections__6 = `<tr><td>`
	connections__7 = `</td></tr>`
)

func ConnectedPlayersView(pageTitle string, players []*sharedjob.Player, wr io.Writer) {

	r, w := io.Pipe()
	go func() {
		buffer := &WriterAsBuffer{w}

		buffer.WriteString(connections__0)

		htmxTemplateFragmentrMeta := "<meta name=\"htmx-config\" content='{\"useTemplateFragments\":true}'>"
		buffer.WriteString(connections__1)
		buffer.WriteString(htmxTemplateFragmentrMeta)
		buffer.WriteString(connections__2)
		WriteEscString(pageTitle, buffer)
		buffer.WriteString(connections__3)
		WriteEscString(pageTitle, buffer)
		buffer.WriteString(connections__4)

		for _, player := range players {
			buffer.WriteString(connections__6)
			WriteEscString(player.Username, buffer)
			buffer.WriteString(connections__7)

		}
		buffer.WriteString(connections__5)

		w.Close()
	}()
	hpp.Format(r, wr)
}
