// Code generated by "jade.go"; DO NOT EDIT.

package ui

import (
	"io"

	"github.com/Joker/hpp"
)

const (
	jobtake__0 = `<div class="modal is-active"><div class="modal-background"></div><div class="modal-content"><div class="box"><h1 class="title">Take job `
	jobtake__2 = `" hx-target="#modal-target"><div class="field"><label class="label" for="user">Username</label><div class="control"><input class="input" type="text" id="user" name="user" placeholder="Admin"/></div><div class="control"><button class="button is-primary" type="submit">Take job</button></div></div></form></div></div></div>`
)

func JobPartTake(jobID string, wr io.Writer) {

	r, w := io.Pipe()
	go func() {
		buffer := &WriterAsBuffer{w}

		buffer.WriteString(jobtake__0)
		WriteEscString(jobID, buffer)
		buffer.WriteString(jobfinish__1)
		WriteAll(jobTakeURL(jobID), true, buffer)
		buffer.WriteString(jobtake__2)

		w.Close()
	}()
	hpp.Format(r, wr)
}
