// Code generated by "jade.go"; DO NOT EDIT.

package ui

import (
	"io"

	"github.com/Joker/hpp"
)

const (
	jobfinish__0 = `<div class="modal is-active"><div class="modal-background"></div><div class="modal-content"><div class="box"><h1 class="title">Finish job `
	jobfinish__1 = `</h1><form hx-post="`
	jobfinish__2 = `" hx-target="#modal-target" hx-select-oob="#jobs-table:afterbegin"><div class="field"><label class="label" for="user">Username</label><div class="control"><input class="input" type="text" id="user" name="user" placeholder="Admin"/></div><div class="control"><button class="button is-primary" type="submit">Finish job</button></div></div></form></div></div></div>`
)

func JobPartFinish(jobID string, wr io.Writer) {

	r, w := io.Pipe()
	go func() {
		buffer := &WriterAsBuffer{w}

		buffer.WriteString(jobfinish__0)
		WriteEscString(jobID, buffer)
		buffer.WriteString(jobfinish__1)
		WriteAll(jobFinishURL(jobID), true, buffer)
		buffer.WriteString(jobfinish__2)

		w.Close()
	}()
	hpp.Format(r, wr)
}
